echo "-----------------------------------"
echo "Tugas 1 SISOP Kelas-A"
echo "-----------------------------------"
echo "Nama: Angela Lisanthoni"
echo "NPM : 21083010032"
echo "-----------------------------------"
echo "notes:"
echo "-----------------------------------"
echo -e "halo dunia!\nIni adalah skrip Bash pertamaku di Linux"
